#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define ZOUL_CONF_USE_CC1200_RADIO          1
#define IEEE802154_CONF_DEFAULT_CHANNEL     2

#define LOG_CONF_LEVEL_RPL      LOG_LEVEL_INFO
#define LOG_CONF_LEVEL_TCPIP    LOG_LEVEL_INFO
#define LOG_CONF_LEVEL_IPV6     LOG_LEVEL_INFO
#define LOG_CONF_LEVEL_MAC      LOG_LEVEL_DBG

#endif /* PROJECT_CONF_H_ */