import io
import sys
import re
import argparse

################################################################################

class message:
    def __init__(self, descriptor, packet_nr, payload_len, rssi, rssi_offset, lqi, tx_power, channel, 
                 channel_center_freq_0, channel_spacing, channel_center_freq_curr, bitrate, symbol_rate,
                 rx_filt_bw, preamble_nibbles, preamble_word, crc_poly, crc_init, sync_word, sync_word_thr,
                 dual_sync_en, sync_bits, freq_dev, mac_hdr_len, rx_link_addr, tx_link_addr):
        self.descriptor = descriptor
        self.packet_nr = packet_nr
        self.payload_len = payload_len
        self.rssi = rssi
        self.rssi_offset = rssi_offset
        self.lqi = lqi
        self.tx_power = tx_power
        self.channel = channel
        self.channel_center_freq_0 = channel_center_freq_0
        self.channel_spacing = channel_spacing
        self.channel_center_freq_curr = channel_center_freq_curr
        self.bitrate = bitrate
        self.symbol_rate = symbol_rate
        self.rx_filt_bw = rx_filt_bw
        self.preamble_nibbles = preamble_nibbles
        self.preamble_word = preamble_word
        self.crc_poly = crc_poly
        self.crc_init = crc_init
        self.sync_word = sync_word
        self.sync_word_thr = sync_word_thr
        self.dual_sync_en = dual_sync_en
        self.sync_bits = sync_bits
        self.freq_dev = freq_dev
        self.mac_hdr_len = mac_hdr_len
        self.rx_link_addr = rx_link_addr
        self.tx_link_addr = tx_link_addr

class received_messages:
    def __init__(self):
        self.messages = []

    def add(self, message):
        for m in self.messages:
            if (m.packet_nr == message.packet_nr):
                raise ValueError("A message with RF descriptor %s and packet nr. %d has already been added" 
                                 % (message.descriptor, message.packet_nr))

        self.messages.append(message)

    def average_rssi(self, amount):

        if (not self.messages):
            raise RuntimeError("There are no received messages")

        if (amount < 0):
            raise ValueError("Cannot process a negative amount of messages")
        elif (amount > len(self.messages)):
            raise ValueError("There are not enough messages to process")

        avg_rssi = 0;

        for m in self.messages[:amount]:
            avg_rssi += m.rssi

        avg_rssi /= amount

        return avg_rssi

    def average_rssi_all(self):
        return self.average_rssi(len(self.messages))

    def packet_loss(self, amount):

        if (not self.messages):
            raise RuntimeError("There are no received messages")

        if (amount < 0):
            raise ValueError("Cannot process a negative amount of messages")
        elif (amount > len(self.messages)):
            raise ValueError("There are not enough messages to process")

        packets_lost = 0

        for i in range(1, amount):
            m = self.messages[i]
            previous_m = self.messages[i - 1]
            packets_lost += m.packet_nr - previous_m.packet_nr - 1

        total = self.messages[amount - 1].packet_nr - self.messages[0].packet_nr + 1

        return packets_lost / total

    def packet_loss_all(self):
        return self.packet_loss(len(self.messages))

    def amount(self):
        return len(self.messages)

################################################################################

parser = argparse.ArgumentParser()
parser.add_argument("logfile", help="The logfile to parse, generated by the scratch program.")
args = parser.parse_args()

LOG_REGEXP = re.compile("^.*?csv-log: (?P<descriptor>.+), (?P<packet_nr>\d+), (?P<payload_len>\d+), (?P<rssi>[+-]?\d+), "
                        "(?P<rssi_offset>[+-]?\d+), (?P<lqi>\d+), (?P<tx_power>\d+), (?P<channel>\d+), (?P<channel_center_freq_0>\d+), "
                        "(?P<channel_spacing>\d+), (?P<channel_center_freq_curr>\d+), (?P<bitrate>\d+), (?P<symbol_rate>\d+), "
                        "(?P<rx_filt_bw>\d+), (?P<preamble_nibbles>\d+), (?P<preamble_word>.+), (?P<crc_poly>.+), (?P<crc_init>.+), "
                        "(?P<sync_word>.+), (?P<sync_word_thr>\d+), (?P<dual_sync_en>\d+), (?P<sync_bits>\d+), (?P<freq_dev>\d+), "
                        "(?P<mac_hdr_len>\d+), (?P<rx_link_addr>.+), (?P<tx_link_addr>.+)")

log_filename = args.logfile
log = open(log_filename, "r")
received_messages = received_messages()

for line in log:
    chomped_line = line.rstrip()

    match = re.match(LOG_REGEXP, chomped_line)
    
    if (match):
        descriptor = match.group("descriptor")
        packet_nr = int(match.group("packet_nr"))
        payload_len = int(match.group("payload_len"))
        rssi = int(match.group("rssi"))
        rssi_offset = int(match.group("rssi_offset"))
        lqi = int(match.group("lqi"))
        tx_power = int(match.group("tx_power"))
        channel = int(match.group("channel"))
        channel_center_freq_0 = int(match.group("channel_center_freq_0"))
        channel_spacing = int(match.group("channel_spacing"))
        channel_center_freq_curr = int(match.group("channel_center_freq_curr"))
        bitrate = int(match.group("bitrate"))
        symbol_rate = int(match.group("symbol_rate"))
        rx_filt_bw = int(match.group("rx_filt_bw"))
        preamble_nibbles = int(match.group("preamble_nibbles"))
        preamble_word = match.group("preamble_word")
        crc_poly = match.group("crc_poly")
        crc_init = match.group("crc_init")
        sync_word = match.group("sync_word")
        sync_word_thr = int(match.group("sync_word_thr"))
        dual_sync_en = int(match.group("dual_sync_en"))
        sync_bits = int(match.group("sync_bits"))
        freq_dev = int(match.group("freq_dev"))
        mac_hdr_len = int(match.group("mac_hdr_len"))
        rx_link_addr = match.group("rx_link_addr")
        tx_link_addr = match.group("tx_link_addr")

        try:
            received_messages.add(message(descriptor, packet_nr, payload_len, rssi, rssi_offset, lqi, tx_power, 
                                  channel, channel_center_freq_0, channel_spacing, channel_center_freq_curr,
                                  bitrate, symbol_rate, rx_filt_bw, preamble_nibbles, preamble_word,
                                  crc_poly, crc_init, sync_word, sync_word_thr, dual_sync_en, sync_bits,
                                  freq_dev, mac_hdr_len, rx_link_addr, tx_link_addr))
        except ValueError as e:
            print(e)

print()
print("Results for {}".format(log_filename))
print("-" * 80)

if (received_messages.amount() > 0):
    print("Amount of received_messages:", received_messages.amount())

    calculated_average_rssi = received_messages.average_rssi_all()
    calculated_packet_loss = received_messages.packet_loss_all()
    
    print("Average RSSI: %.2f" % (calculated_average_rssi))
    print("Packet loss rate: %.2f %%" % (calculated_packet_loss * 100))
else:
    print("No messages received")

print()
